name: github_actions_gtest-Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  # Release, Debug, RelWithDebInfo, etc.
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install pip and build dependencies
      run: sudo apt update -y && sudo apt install -y python3-pip build-essential g++ && sudo pip install cmake
    - uses: actions/checkout@v2
    - name: Configure with CMake
      run: cmake -S . -B build/${{env.BUILD_TYPE}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build and Install
      run: cmake --build build/${{env.BUILD_TYPE}} && cmake --install build/${{env.BUILD_TYPE}} --prefix bin/
    - name: Run Unit Tests
      run: ./bin/core_test
